### ISSUE TITLE
adjust IP for terms.tdwg.org subdomain

### ISSUE THREAD

**Issue by DavidFichtmueller** [tdwg/infrastructure#96]
The TDWG Terms Wiki runs on the Biowikifarm which due to some technical chances in the MfN had to change its public IP. The new IP is 212.201.100.125 and it needs to be migrated very soon, preferably today.

For further questions, please contact Falko Glöckler.

**Comment by MattBlissett** [comment]
Done, but note the new IP is not working correctly (504 Gateway Timeout).

**Comment by DavidFichtmueller** [comment]
Thank you. Yes the server is still having some issues. The colleagues at the MfN are currently restructuring the infrastructure. The issues were also present with the old IP.
